import { useEffect, useState } from "react";
import { supabase } from "../supabaseClient";
import { useNavigate } from "react-router-dom";

export default function ResetPassword() {
  const [ready,setReady]=useState(false),[password,setPassword]=useState(""),[confirm,setConfirm]=useState(""),[loading,setLoading]=useState(false);
  const [show,setShow]=useState(false),[showConfirm,setShowConfirm]=useState(false),[message,setMessage]=useState("");
  const navigate=useNavigate();

  useEffect(()=>{supabase.auth.getSession().then(({data})=>setReady(Boolean(data.session)));const {data}=supabase.auth.onAuthStateChange(e=>{if(e==="PASSWORD_RECOVERY")setReady(true)});return()=>data.subscription.unsubscribe()},[]);

  const submit=async(e)=>{e.preventDefault();if(password.length<8)return alert("Password must be at least 8 characters.");if(password.length>64)return alert("Password cannot exceed 64 characters.");if(password!==confirm)return alert("Passwords do not match.");setLoading(true);try{const {error}=await supabase.auth.updateUser({password});if(error)throw error;setMessage("Your password has been updated successfully.");setTimeout(()=>navigate("/"),1200)}catch(err){console.error(err);setMessage("The reset link is invalid or has expired. Please request a new one.")}finally{setLoading(false)}};

  return <div style={s.container}><div style={s.overlay}/><div style={s.card}><h1 style={s.title}>Reset Password</h1>{!ready?<><p style={s.text}>This reset link is invalid or has expired.</p><button onClick={()=>navigate("/forgot-password")} style={s.button}>Request New Link</button></>:<form onSubmit={submit}>
  <label style={s.label}>New Password <span style={s.req}>*</span></label><div style={s.wrap}><input type={show?"text":"password"} required minLength={8} maxLength={64} autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Enter new password" style={s.input}/><button type="button" onClick={()=>setShow(v=>!v)} style={s.eye}>{show?"Hide":"Show"}</button></div>
  <label style={s.label2}>Confirm Password <span style={s.req}>*</span></label><div style={s.wrap}><input type={showConfirm?"text":"password"} required minLength={8} maxLength={64} autoComplete="new-password" value={confirm} onChange={e=>setConfirm(e.target.value)} placeholder="Re-enter password" style={s.input}/><button type="button" onClick={()=>setShowConfirm(v=>!v)} style={s.eye}>{showConfirm?"Hide":"Show"}</button></div>
  <div style={s.help}>8–64 characters, including uppercase, lowercase, number, and special character.</div><button disabled={loading} style={s.button}>{loading?"Updating...":"Update Password"}</button></form>}{message&&<div style={s.message}>{message}</div>}<button onClick={()=>navigate("/")} style={s.back}>Back to Login</button></div></div>
}
const s={container:{minHeight:"100vh",backgroundImage:"url('/bg.jpg')",backgroundSize:"cover",backgroundPosition:"center",display:"flex",justifyContent:"center",alignItems:"center",position:"relative",padding:"24px"},overlay:{position:"fixed",inset:0,background:"rgba(0,0,0,.58)"},card:{position:"relative",zIndex:1,width:"100%",maxWidth:"420px",background:"#fff",padding:"36px",borderRadius:"14px",boxShadow:"0 18px 45px rgba(0,0,0,.28)",borderTop:"4px solid #f97316",boxSizing:"border-box"},title:{textAlign:"center",color:"#111827"},text:{color:"#6b7280",fontSize:"14px",textAlign:"center"},label:{display:"block",marginBottom:"7px",fontSize:"13px",fontWeight:"600",color:"#374151"},label2:{display:"block",margin:"16px 0 7px",fontSize:"13px",fontWeight:"600",color:"#374151"},req:{color:"#dc2626"},wrap:{position:"relative"},input:{width:"100%",boxSizing:"border-box",padding:"12px 55px 12px 13px",borderRadius:"8px",border:"1px solid #d1d5db"},eye:{position:"absolute",right:8,top:"50%",transform:"translateY(-50%)",border:0,background:"transparent",color:"#ea580c",fontWeight:"700"},help:{marginTop:6,fontSize:"11px",color:"#6b7280"},button:{width:"100%",marginTop:18,padding:"12px",border:0,borderRadius:"8px",background:"#f97316",color:"#fff",fontWeight:"700"},message:{marginTop:16,padding:12,background:"#f3f4f6",borderRadius:8,fontSize:13,color:"#374151"},back:{display:"block",width:"100%",marginTop:18,padding:10,border:0,background:"transparent",color:"#ea580c",fontWeight:"600"}};
